# Assignment 0

### <span style="color:chocolate"> Submission requirements </span>

Your work will not be graded if your notebook doesn't include output. In other words, <span style="color:red"> make sure to rerun your notebook before submitting to Gradescope </span> (Note: if you are using Google Colab: go to Edit > Notebook Settings  and uncheck Omit code cell output when saving this notebook, otherwise the output is not printed).

Additional points may be deducted if these requirements are not met:
    
* Comment your code;
* Each graph should have a title, labels for each axis, and (if needed) a legend. Each graph should be understandable on its own;
* Try and minimize the use of the global namespace (meaning, keep things inside functions).
---

### Import libraries

In [1]:
import numpy as np

---
### <span style="color:chocolate">Exercise 1:</span> Homogenous data types (10 points)

1. Create a numpy array (my_array1) containing only integer values. Print the shape of the array and the type of its elements;
2. Create another numpy array (my_array2) containing a mix of integer and string values. Print the shape of the array and the type of its elements. Comment on the type of its elements.

In [2]:
# YOUR CODE HERE

# 1)
# Create the array using np.arange. This creates 20 integer values beginning at zero:
my_array1 = np.arange(20)
print('1) my_array1: ', my_array1)

# Print the shape of the array and type of its elements:
print('The shape of my_array1 is:', my_array1.shape)
print('The data type of my_array1 is:', my_array1.dtype)
print("*"*50)

# 2) Create an array with a mix of integers and strings: 
my_array2 = np.array([1, 'two', 3, 'four', 5, 'six'])
print('2) my_array2: ', my_array2)

# Print the shape of the array and type of its elements:
print('The shape of my_array2 is:', my_array2.shape)
print('The data type of my_array2 is:', my_array2.dtype)

# The data type of my_array2 is listed as "<U21." 
# The reason for this is because numpy automatically tries to find a data type that can uniformly represent all items in the array. 
# Because there is a mix of strings and integers, numpy is reassigning the integers into strings.

1) my_array1:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
The shape of my_array1 is: (20,)
The data type of my_array1 is: int64
**************************************************
2) my_array2:  ['1' 'two' '3' 'four' '5' 'six']
The shape of my_array2 is: (6,)
The data type of my_array2 is: <U21


---
#### <span style="color:chocolate">Exercise 2:</span> The size attribute (10 points)

Create a numpy array (my_array3) and print its shape, size, and data type. What does size represent?

In [3]:
# YOUR CODE HERE

# Create the array using np.arange. This creates 20 integer values beginning at zero:
my_array3 = np.arange(20)

# Print the shape, size, and data type:
print('The shape of my_array3 is:', my_array3.shape)
print('The size of my_array3 is:', my_array3.size)
print('The data type of my_array3 is:', my_array3.dtype)

# The size of an array represents the total number of elements in that array.

The shape of my_array3 is: (20,)
The size of my_array3 is: 20
The data type of my_array3 is: int64


---
#### <span style="color:chocolate">Exercise 3:</span> Tabular data layout (10 points)

Create a tabular data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:
* the first input is num_samples, and
* the second input is num_features. 

Print the shape of the array.

In [4]:
# already defined first and second inputs
num_samples = 100
num_features = 17

# YOUR CODE HERE

# Create the table using the np.random.random function:
my_table1 = np.random.random(size = (num_samples, num_features))
print('my_table1:\n', my_table1)
print('*' * 50)

# Print the shape of the table:
print('The shape of my_table1 is:', my_table1.shape)

my_table1:
 [[0.84625936 0.32769956 0.77374803 ... 0.88765647 0.50041651 0.41494883]
 [0.95102894 0.31142221 0.35979241 ... 0.93626623 0.42060315 0.59736037]
 [0.86810423 0.60872624 0.03567826 ... 0.7319391  0.60528389 0.86680627]
 ...
 [0.56755307 0.23599543 0.76777717 ... 0.52581956 0.92273491 0.19238525]
 [0.34042485 0.11099622 0.13925124 ... 0.3120834  0.93619492 0.79126023]
 [0.46462051 0.96334432 0.55185684 ... 0.53769926 0.55718048 0.24437064]]
**************************************************
The shape of my_table1 is: (100, 17)


---
#### <span style="color:chocolate">Exercise 4:</span> Image data layout (10 points)

Create an image data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:

* the first input is num_images;
* the second input is num_rows;
* the third input is num_cols;
* the fourth input is num_channels.

Print the shape of the array.

In [5]:
# already defined inputs
num_images = 100
num_rows = 256
num_cols = 256
num_channels = 3 #(RGB)

# YOUR CODE HERE

# Create the table using the np.random.random function:
my_table2 = np.random.random(size = (num_images, num_rows, num_cols, num_channels))
print('my_table2:\n', my_table2)
print('*' * 50)

# Print the shape of the table:
print('The shape of my_table2 is:', my_table2.shape)

my_table2:
 [[[[0.07284565 0.35205273 0.48887776]
   [0.00592627 0.31525203 0.18585993]
   [0.27060606 0.04900755 0.72663629]
   ...
   [0.23893219 0.3017157  0.42701451]
   [0.32143174 0.18682881 0.11753484]
   [0.55339018 0.79802543 0.04555624]]

  [[0.56850174 0.37724682 0.78319402]
   [0.71184396 0.09921474 0.60298905]
   [0.08734802 0.15405115 0.33072039]
   ...
   [0.75037035 0.89228868 0.41961495]
   [0.28458952 0.51071165 0.60003239]
   [0.74579607 0.08947436 0.60271449]]

  [[0.90295242 0.06423093 0.43647154]
   [0.80459246 0.78858625 0.46111025]
   [0.5819954  0.29426044 0.2421269 ]
   ...
   [0.26656857 0.79984331 0.21371973]
   [0.99899288 0.92872428 0.65387064]
   [0.31928228 0.71218824 0.58532416]]

  ...

  [[0.09343259 0.05858375 0.89283409]
   [0.44091746 0.99059904 0.69542833]
   [0.36216859 0.90657131 0.8957914 ]
   ...
   [0.26488467 0.63617509 0.82388409]
   [0.81439098 0.54460995 0.70126649]
   [0.12019946 0.96250865 0.12711525]]

  [[0.39016254 0.97763617 0.65723

---
#### <span style="color:chocolate">Exercise 5: </span>Mathematical operations on numpy arrays (15 points)

Create a (3, 2) numpy array (you can name it my_array4) containing only integer values. Perform the following tasks:

1. Print the shape of the array;
2. Print the sum of all elements (hint: the axis argument is set to None);
3. Print the sum of all elements by column;
3. Print the sum of all elements by row and change the type of the resulting array elements to float;
5. Print the first row of the array;
6. Print the second row of the array;
7. Select the element at position (1, 0);
8. Modify the element at position (2, 1) by setting its value to 10 and print the array again;
9. Loop over elements in the array. Print the output.

In [6]:
# YOUR CODE HERE

# Create the array of size (3,2) with random integers:
my_array4 = np.random.randint(0, 10, size=(3,2))
print('original my_array4:\n', my_array4)
print("*"*50)

# 1) Print the shape of the array:
print('1) The shape of my_array4 is: ', my_array4.shape)
print("*"*50)

# 2) Print the sum of all elements:
print('2) The sum of all elements in my_array4 is: ', my_array4.sum(axis=None))
print("*"*50)

# 3) Print the sum of all elements by column:
print('3) The sum of all elements in my_array4, by column, is: ', my_array4.sum(axis=0))
print("*"*50)

# 4) Print the sum of all elements by row: 
print('4a) The sum of all elements in my_array4, by row, is: ', my_array4.sum(axis=1))
# Change the type of the resulting array elements to float:
print('4b) Changing the type to float: ', my_array4.sum(axis=1).astype(float))
print("*"*50)

# 5) Print the first row of the array:
print('5) The first row of my_array4 is: ', my_array4[0])
print("*"*50)

# 6) Print the second row of the array:
print('6) The second row of my_array4 is: ', my_array4[1])
print("*"*50)

# 7) Select the element at position (1,0): 
print('7) The element at position (1,0) is: ', my_array4[1,0])
print("*"*50)

# 8) Modify the element at position (2,1) by setting it's value to 10 and printing the array again:
my_array4[2, 1] = 10
print('8) Setting the element at (2,1) to 10. The new array is:')
print(my_array4)
print("*"*50)

# 9) Loop over all elements in the array and print the output:
print('9) Loop through the array and print each element: ')
for i in my_array4:
    for j in i:
        print(j)

original my_array4:
 [[6 9]
 [3 2]
 [7 0]]
**************************************************
1) The shape of my_array4 is:  (3, 2)
**************************************************
2) The sum of all elements in my_array4 is:  27
**************************************************
3) The sum of all elements in my_array4, by column, is:  [16 11]
**************************************************
4a) The sum of all elements in my_array4, by row, is:  [15  5  7]
4b) Changing the type to float:  [15.  5.  7.]
**************************************************
5) The first row of my_array4 is:  [6 9]
**************************************************
6) The second row of my_array4 is:  [3 2]
**************************************************
7) The element at position (1,0) is:  3
**************************************************
8) Setting the element at (2,1) to 10. The new array is:
[[ 6  9]
 [ 3  2]
 [ 7 10]]
**************************************************
9) Loop through the array 

You can find more examples here: https://numpy.org/doc/stable/reference/routines.math.html

---
#### <span style="color:chocolate">Exercise 6:</span> Create arrays (15 points)

1. Create and print a (3,2) numpy array of pixel values between 0 and 1.
2. Create and print a (27,) numpy array representing years from 1991 to 2017
3. Create and print a (3, 5, 10) empty numpy array
4. Create and print a (3, 5, 10) numpy array of ones
5. Create and print an array with a constant value (let's say 5) using np.ones()
6. Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.


In [7]:
# YOUR CODE HERE

#1) Create and print a (3,2) numpy array of pixel values between 0 and 1:
my_array5 = np.random.random(size = (3,2))
print('1) (3,2) numpy array:\n', my_array5)
print("*"*50)

#2) Create and print a (27, ) array representing the years from 1991 to 2017:
my_array6 = np.arange(1991, 2018, 1)
print('2) Array of years from 1991 to 2017:\n', my_array6)
print("*"*50)

# 3) Create and print a (3, 5, 10) empty numpy array:
my_array7 = np.empty(shape=(3,5,10))
print('3) (3, 5, 10) empty numpy array:\n', my_array7)
print("*"*50)

# 4) Create and print a (3, 5, 10) numpy array of ones:
my_array8 = np.ones(shape=(3,5,10))
print('4) (3, 5, 10) numpy array of ones:\n', my_array8)
print("*"*50)

# 5) Create and print an array with a constant value (let's say 5) using np.ones():
my_array9 = np.ones(shape=(3,5,10)) * 5
print('5) Array with a constant value 5:\n', my_array9)
print("*"*50)

# 6) Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.
mean = 0
std = 1
sample = 10
my_array10 = np.random.normal(mean, std, sample)
print('6) Array with random numbers from normal distribution:\n', my_array10)

1) (3,2) numpy array:
 [[0.21186442 0.53970299]
 [0.86981163 0.3933884 ]
 [0.07781645 0.74534631]]
**************************************************
2) Array of years from 1991 to 2017:
 [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
**************************************************
3) (3, 5, 10) empty numpy array:
 [[[0.00000000e+000 6.99102889e-321 0.00000000e+000 6.66988622e-322
   6.94126043e-310 1.16095484e-028 4.23917406e+088 5.83332263e+025
   5.49880583e-072 5.28556325e+180]
  [8.82085766e+199 8.96856757e-096 9.10016855e+276 1.95132487e+227
   1.69431834e-152 4.73667725e+164 7.09514562e-077 1.90372876e+136
   2.59345485e+161 5.28595592e-085]
  [1.01445441e+242 9.16527479e+199 8.96856657e-096 8.82142681e+199
   2.05077201e-115 1.89122258e+219 4.83245960e+276 4.46008788e+217
   4.23978203e-051 6.96770842e+252]
  [1.36426988e-052 3.60369739e-067 5.28556325e+180 8.82085766e+199
   8.1417656

---
#### <span style="color:chocolate">Exercise 7:</span> Reshape arrays (10 points)

Consider the following array:

In [8]:
years = np.arange(1991, 2018, 1)
print(years.shape)

(27,)


Perform the following operations on this array:
    
1. Create 3 nested arrays, each of size (3, 3). Call this array years_3d;
2. Convert the years_3d array to a flat 1D array. Call this array years_1d;
3. Add a new axis (in front) to the years_1d array. Call this array years_2d;
4. Remove the first axis from years_2d array. Call this array years_1d.

For each exercise print the array and its shape.

In [9]:
# YOUR CODE HERE

# 1) Create 3 nested arrays, each of size (3, 3). Call this array years_3d:
years_3d = years.reshape((3,3,3))
print('1) years_3d:\n', years_3d) 
print('The shape of years_3d is: ', years_3d.shape)
print("*"*50)

# 2) Convert the years_3d array to a flat 1D array and call it years_1d:
years_1d = years_3d.flatten()
print('2) years_1d:\n', years_1d)
print('The shape of years_1d is: ', years_1d.shape)
print("*"*50)

# 3) Add a new axis (in front) to the years_1d array. Call this array years_2d:
years_2d = years_1d[np.newaxis, :]
print("3) years_2d:\n", years_2d)
print("The shape of years_2d:", years_2d.shape)
print("*"*50)

# 4) Remove the first axis from years_2d. Call this array years_1d:
years_1d = years_2d.squeeze()
print('4) years_1d:\n', years_1d)
print('The shape of years_1d is: ', years_1d.shape)


1) years_3d:
 [[[1991 1992 1993]
  [1994 1995 1996]
  [1997 1998 1999]]

 [[2000 2001 2002]
  [2003 2004 2005]
  [2006 2007 2008]]

 [[2009 2010 2011]
  [2012 2013 2014]
  [2015 2016 2017]]]
The shape of years_3d is:  (3, 3, 3)
**************************************************
2) years_1d:
 [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
The shape of years_1d is:  (27,)
**************************************************
3) years_2d:
 [[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
  2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]]
The shape of years_2d: (1, 27)
**************************************************
4) years_1d:
 [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
The shape of years_1d is:  (27,)


---
#### <span style="color:chocolate">Exercise 8:</span> Joining arrays (10 points)

Provide 8 examples that use the methods <span style="color:cornflowerBlue">np.concatenate()</span> and <span style="color:cornflowerBlue">np.stack()</span>. Note: create 4 examples using each method.

In [10]:
# YOUR CODE HERE

# Create two random arrays of integer values:
array_a = np.random.randint(0, 10, size=(2,2))
print('example array_a:\n', array_a)
array_b = np.random.randint(0, 10, size=(2,2))
print('example array_b:\n', array_b)
print('*' * 50)

# Concatenate - Example 1: Concatenate along the column
array_c = np.concatenate((array_a, array_b), axis=0)
print('Example 1: Concatenate along the column:\n', array_c)

# Concatenate - Example 2: Concatenate along the rows
array_c = np.concatenate((array_a, array_b), axis=1)
print('Example 2: Concatenate along the rows:\n', array_c)

# Concatenate - Example 3: Concatenate into a single dimension
array_c = np.concatenate((array_a, array_b), axis=None)
print('Example 3: Concatenate into a single dimension:\n', array_c)

# Concatenate - Example 4: Concatenate into a single dimension, in reverse order
array_c = np.concatenate((array_b, array_a), axis=None)
print('Example 4: Concatenate into a single dimension, in reverse order:\n', array_c)
print('*' * 50)

# Stack - Example 1: Stack along axis = 0
array_c = np.stack((array_a, array_b), axis=0)
print('Example 1: Stack along axis = 0:\n', array_c)

# Stack - Example 2: Stack along axis = 1
array_c = np.stack((array_a, array_b), axis=1)
print('Example 2: Stack along axis = 1:\n', array_c)

# Stack - Example 3: Stack along axis = 2
array_c = np.stack((array_a, array_b), axis=2)
print('Example 3: Stack along axis = 2:\n', array_c)

# Stack - Example 4: Stack along axis 2, with a Transposed array
array_c = np.stack((array_a, array_b.T), axis=2)
print('Example 3: Stack along axis = 2, with a Transposed array:\n', array_c)

example array_a:
 [[7 3]
 [2 5]]
example array_b:
 [[9 1]
 [5 6]]
**************************************************
Example 1: Concatenate along the column:
 [[7 3]
 [2 5]
 [9 1]
 [5 6]]
Example 2: Concatenate along the rows:
 [[7 3 9 1]
 [2 5 5 6]]
Example 3: Concatenate into a single dimension:
 [7 3 2 5 9 1 5 6]
Example 4: Concatenate into a single dimension, in reverse order:
 [9 1 5 6 7 3 2 5]
**************************************************
Example 1: Stack along axis = 0:
 [[[7 3]
  [2 5]]

 [[9 1]
  [5 6]]]
Example 2: Stack along axis = 1:
 [[[7 3]
  [9 1]]

 [[2 5]
  [5 6]]]
Example 3: Stack along axis = 2:
 [[[7 9]
  [3 1]]

 [[2 5]
  [5 6]]]
Example 3: Stack along axis = 2, with a Transposed array:
 [[[7 9]
  [3 5]]

 [[2 1]
  [5 6]]]


---
#### <span style="color:chocolate">Numpy broadcasting</span> 

The term broadcasting describes how NumPy treats arrays during arithmetic operations. You can find more here:  https://numpy.org/doc/stable/user/basics.broadcasting.html

In [11]:
# multiplying an array with a scalar
years = np.arange(1991, 2018, 1)
years * 1

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])

In [12]:
# adding a scalar
years + 2

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019])

In [13]:
# many arithmetic operations are applied element wise on a pair of arrays
a = np.arange(3)
print('Array a:', a)
b = np.arange(3)
print('Array b:', b)
print('Sum of a and b:', a+b)

Array a: [0 1 2]
Array b: [0 1 2]
Sum of a and b: [0 2 4]


In [14]:
# another example
a = np.ones((3, 3))
print('Array a:', a)
b = np.arange(3)
print('\nArray b:', b)
print('\nSum of a and b:', a+b)

Array a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array b: [0 1 2]

Sum of a and b: [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


---
#### <span style="color:chocolate">Exercise 9:</span> Numpy array standardization (10 points)

Consider the following (10, 4) array:

In [15]:
my_array = np.random.random((10, 4))
print('my_array shape: ', my_array.shape)
my_array

my_array shape:  (10, 4)


array([[0.22678473, 0.49109728, 0.3633915 , 0.49212065],
       [0.86279109, 0.06680263, 0.40517015, 0.88268843],
       [0.50557947, 0.42660164, 0.40836299, 0.75760608],
       [0.60464345, 0.39328466, 0.8086688 , 0.36359121],
       [0.02726183, 0.03807972, 0.47524488, 0.45967623],
       [0.4457536 , 0.67146108, 0.32987362, 0.79669594],
       [0.39974456, 0.33627203, 0.93345313, 0.08176876],
       [0.51888713, 0.34164059, 0.88640495, 0.49809877],
       [0.67751269, 0.071814  , 0.17764496, 0.61740227],
       [0.92745289, 0.2503341 , 0.5128026 , 0.13398652]])

Peform the following operations on this array:
1. Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
2. Standardize and print the array and its shape using the mean and std you computed above.

In [16]:
np.random.seed(seed=1)

# YOUR CODE HERE

#1) Compute and print the mean and std for each column:
my_array_mean = my_array.mean(axis=0, keepdims=True)
print('1a) The mean of each column is:\n', my_array_mean)

my_array_std = my_array.std(axis=0, keepdims=True)
print('1b) The Standard Deviation of each column is:\n', my_array_std)
print('*' * 50)

# 2) Standardize and print the array and its shape using the mean and std you computed above: 
standardized_my_array = (my_array - my_array_mean)/(my_array_std)
print('2) The Standardized array is: \n', standardized_my_array)

1a) The mean of each column is:
 [[0.51964114 0.30873877 0.53010176 0.50836349]]
1b) The Standard Deviation of each column is:
 [[0.25776855 0.19468853 0.24353441 0.25359533]]
**************************************************
2) The Standardized array is: 
 [[-1.13612159  0.93666795 -0.68454499 -0.06405024]
 [ 1.33123281 -1.24268309 -0.51299365  1.47607192]
 [-0.05455154  0.60539192 -0.49988323  0.98283589]
 [ 0.32976214  0.43426231  1.14385087 -0.5708791 ]
 [-1.91016055 -1.39021571 -0.22525308 -0.191988  ]
 [-0.28664298  1.86309024 -0.82217599  1.13697856]
 [-0.46513273  0.14142208  1.65623977 -1.68218682]
 [-0.00292516  0.16899722  1.46305072 -0.04047677]
 [ 0.61245465 -1.21694262 -1.44725669  0.42997159]
 [ 1.58208495 -0.2999903  -0.07103374 -1.47627703]]


----
#### <span style="color:chocolate">Bonus question:</span> Advanced (20 points)

Consider the following image:

In [17]:
my_image = np.arange(0, 1, 0.04).reshape(5,5)
print(my_image)
my_image.shape

[[0.   0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]


(5, 5)

Perform the following operations on this image (do not overwrite the original image):

1. Crop by using a border of size 1;
2. Crop by using a border of size 2;
3. Reverse the column order;
4. set to 0.5 elements divizible by 2.

In [18]:
# YOUR CODE HERE

# Finding the 'length' and 'height' of the image. In the code above, it is locked to (5,5), but I wanted to make a more general formula that could change with the user input:
my_image_height = my_image.shape[0]
my_image_length = my_image.shape[1]

# Setting the border to 1:
border = 1

# 1) Crop by using a border of size 1:
border_1 = my_image[border:my_image_length - border, border:my_image_height - border]
print('1) Image with border of 1:\n', border_1)
print('*' * 50)

# 2) Crop by using a border of size 2:

# Setting a new border size:
border = 2

border_2 = my_image[border:my_image_length - border, border:my_image_height - border]
print('2) Image with border of 1:\n', border_2)
print('*' * 50)

# 3) Reverse the column order: 
reverse_my_image = np.flip(my_image, axis=1)
print('3) Reversed image:\n', reverse_my_image)
print('*' * 50)

# 4) Set elements divisible by 2 to 0.5:
my_image[my_image % 2 == 0] = 5
print('4) Setting all elements that are divisible by 2 equal to 5:\n', my_image)


1) Image with border of 1:
 [[0.24 0.28 0.32]
 [0.44 0.48 0.52]
 [0.64 0.68 0.72]]
**************************************************
2) Image with border of 1:
 [[0.48]]
**************************************************
3) Reversed image:
 [[0.16 0.12 0.08 0.04 0.  ]
 [0.36 0.32 0.28 0.24 0.2 ]
 [0.56 0.52 0.48 0.44 0.4 ]
 [0.76 0.72 0.68 0.64 0.6 ]
 [0.96 0.92 0.88 0.84 0.8 ]]
**************************************************
4) Setting all elements that are divisible by 2 equal to 5:
 [[5.   0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]
