# Assignment 0

### <span style="color:chocolate"> Submission requirements </span>

Your work will not be graded if your notebook doesn't include output. In other words, <span style="color:red"> make sure to rerun your notebook before submitting to Gradescope </span> (Note: if you are using Google Colab: go to Edit > Notebook Settings  and uncheck Omit code cell output when saving this notebook, otherwise the output is not printed).

Additional points may be deducted if these requirements are not met:
    
* Comment your code;
* Each graph should have a title, labels for each axis, and (if needed) a legend. Each graph should be understandable on its own;
* Try and minimize the use of the global namespace (meaning, keep things inside functions).
---

### Import libraries

In [1]:
import numpy as np

---
### <span style="color:chocolate">Exercise 1:</span> Homogenous data types (10 points)

1. Create a numpy array (my_array1) containing only integer values. Print the shape of the array and the type of its elements;
2. Create another numpy array (my_array2) containing a mix of integer and string values. Print the shape of the array and the type of its elements. Comment on the type of its elements.

In [2]:
# YOUR CODE HERE

# 1)
# Create the array using np.arange. This creates 20 integer values beginning at zero:
my_array1 = np.arange(20)
print('1) my_array1: ', my_array1)

# Print the shape of the array and type of its elements:
print('The shape of my_array1 is:', my_array1.shape)
print('The data type of my_array1 is:', my_array1.dtype)
print("*"*50)

# 2)
# Create an array with a mix of integers and strings: 
my_array2 = np.array([1, 'two', 3, 'four', 5, 'six'])
print('2) my_array2: ', my_array2)

# Print the shape of the array and type of its elements:
print('The shape of my_array2 is:', my_array2.shape)
print('The data type of my_array2 is:', my_array2.dtype)

# The data type of my_array2 is listed as "<U21." 
# The reason for this is because numpy automatically tries to find a data type that can uniformly represent all items in the array. 
# Because there is a mix of strings and integers, numpy is reassigning the integers into strings.

1) my_array1:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
The shape of my_array1 is: (20,)
The data type of my_array1 is: int64
**************************************************
2) my_array2:  ['1' 'two' '3' 'four' '5' 'six']
The shape of my_array2 is: (6,)
The data type of my_array2 is: <U21


---
#### <span style="color:chocolate">Exercise 2:</span> The size attribute (10 points)

Create a numpy array (my_array3) and print its shape, size, and data type. What does size represent?

In [3]:
# YOUR CODE HERE

# Create the array using np.arange. This creates 20 integer values beginning at zero:
my_array3 = np.arange(20)

# Print the shape, size, and data type:
print('The shape of my_array3 is:', my_array3.shape)
print('The size of my_array3 is:', my_array3.size)
print('The data type of my_array3 is:', my_array3.dtype)

# The size of an array represents the total number of elements in that array.

The shape of my_array3 is: (20,)
The size of my_array3 is: 20
The data type of my_array3 is: int64


---
#### <span style="color:chocolate">Exercise 3:</span> Tabular data layout (10 points)

Create a tabular data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:
* the first input is num_samples, and
* the second input is num_features. 

Print the shape of the array.

In [4]:
# already defined first and second inputs
num_samples = 100
num_features = 17

# YOUR CODE HERE

# Create the table using the np.random.random function:
my_table1 = np.random.random(size = (num_samples, num_features))
print('my_table1:\n', my_table1)
print('*' * 50)

# Print the shape of the table:
print('The shape of my_table1 is:', my_table1.shape)

my_table1:
 [[0.89800447 0.56688435 0.66323021 ... 0.70249526 0.6507762  0.44965235]
 [0.39151144 0.11888167 0.27259481 ... 0.90720756 0.69706519 0.92565356]
 [0.4986693  0.8835683  0.6771227  ... 0.78484592 0.74498142 0.36211056]
 ...
 [0.84871998 0.43464851 0.80634504 ... 0.81245532 0.4927778  0.1365656 ]
 [0.15622493 0.17732387 0.70356899 ... 0.15402016 0.58924613 0.96986859]
 [0.7955837  0.60243317 0.6974812  ... 0.2361031  0.8198876  0.29271625]]
**************************************************
The shape of my_table1 is: (100, 17)


---
#### <span style="color:chocolate">Exercise 4:</span> Image data layout (10 points)

Create an image data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:

* the first input is num_images;
* the second input is num_rows;
* the third input is num_cols;
* the fourth input is num_channels.

Print the shape of the array.

In [5]:
# already defined inputs
num_images = 100
num_rows = 256
num_cols = 256
num_channels = 3 #(RGB)

# YOUR CODE HERE

# Create the table using the np.random.random function:
my_table2 = np.random.random(size = (num_images, num_rows, num_cols, num_channels))
print('my_table2:\n', my_table2)
print('*' * 50)

# Print the shape of the table:
print('The shape of my_table2 is:', my_table2.shape)

my_table2:
 [[[[0.04186233 0.0865572  0.4080444 ]
   [0.01992859 0.79220909 0.98383964]
   [0.60954171 0.05497996 0.75837679]
   ...
   [0.23022945 0.5920808  0.79862689]
   [0.98145347 0.70916405 0.06066587]
   [0.62628011 0.85298401 0.49555372]]

  [[0.50366384 0.71905886 0.73452481]
   [0.84419361 0.27995443 0.63699411]
   [0.71870994 0.12990569 0.52342434]
   ...
   [0.53763827 0.9280538  0.82969052]
   [0.59534628 0.38992283 0.75265911]
   [0.66176009 0.67203883 0.40224618]]

  [[0.8246932  0.44591198 0.67000455]
   [0.88034817 0.12587741 0.05451552]
   [0.56816837 0.92406824 0.3846697 ]
   ...
   [0.69585971 0.9525498  0.39312061]
   [0.41711223 0.96765713 0.1191861 ]
   [0.35982869 0.53471494 0.60391814]]

  ...

  [[0.29998157 0.59372696 0.99385602]
   [0.83275568 0.54025041 0.04700101]
   [0.12078749 0.52724523 0.20004602]
   ...
   [0.58311504 0.79794199 0.40924061]
   [0.60578687 0.71227573 0.72267727]
   [0.55328795 0.44218819 0.42307126]]

  [[0.04392585 0.32917328 0.82394

---
#### <span style="color:chocolate">Exercise 5: </span>Mathematical operations on numpy arrays (15 points)

Create a (3, 2) numpy array (you can name it my_array4) containing only integer values. Perform the following tasks:

1. Print the shape of the array;
2. Print the sum of all elements (hint: the axis argument is set to None);
3. Print the sum of all elements by column;
3. Print the sum of all elements by row and change the type of the resulting array elements to float;
5. Print the first row of the array;
6. Print the second row of the array;
7. Select the element at position (1, 0);
8. Modify the element at position (2, 1) by setting its value to 10 and print the array again;
9. Loop over elements in the array. Print the output.

In [6]:
# YOUR CODE HERE

# Create the array of size (3,2) with random integers:
my_array4 = np.random.randint(0, 10, size=(3,2))
print('original my_array4:\n', my_array4)
print("*"*50)

# 1) Print the shape of the array:
print('1) The shape of my_array4 is: ', my_array4.shape)
print("*"*50)

# 2) Print the sum of all elements:
print('2) The sum of all elements in my_array4 is: ', my_array4.sum(axis=None))
print("*"*50)

# 3) Print the sum of all elements by column:
print('3) The sum of all elements in my_array4, by column, is: ', my_array4.sum(axis=0))
print("*"*50)

# 4) Print the sum of all elements by row: 
print('4a) The sum of all elements in my_array4, by row, is: ', my_array4.sum(axis=1))
# Change the type of the resulting array elements to float:
print('4b) Changing the type to float: ', my_array4.sum(axis=1).astype(float))
print("*"*50)

# 5) Print the first row of the array:
print('5) The first row of my_array4 is: ', my_array4[0])
print("*"*50)

# 6) Print the second row of the array:
print('6) The second row of my_array4 is: ', my_array4[1])
print("*"*50)

# 7) Select the element at position (1,0): 
print('7) The element at position (1,0) is: ', my_array4[1,0])
print("*"*50)

# 8) Modify the element at position (2,1) by setting it's value to 10 and printing the array again:
my_array4[2, 1] = 10
print('8) Setting the element at (2,1) to 10. The new array is:')
print(my_array4)
print("*"*50)

# 9) Loop over all elements in the array and print the output:
print('9) Loop through the array and print each element: ')
for i in my_array4:
    for j in i:
        print(j)

original my_array4:
 [[7 5]
 [5 7]
 [2 1]]
**************************************************
1) The shape of my_array4 is:  (3, 2)
**************************************************
2) The sum of all elements in my_array4 is:  27
**************************************************
3) The sum of all elements in my_array4, by column, is:  [14 13]
**************************************************
4a) The sum of all elements in my_array4, by row, is:  [12 12  3]
4b) Changing the type to float:  [12. 12.  3.]
**************************************************
5) The first row of my_array4 is:  [7 5]
**************************************************
6) The second row of my_array4 is:  [5 7]
**************************************************
7) The element at position (1,0) is:  5
**************************************************
8) Setting the element at (2,1) to 10. The new array is:
[[ 7  5]
 [ 5  7]
 [ 2 10]]
**************************************************
9) Loop through the array 

You can find more examples here: https://numpy.org/doc/stable/reference/routines.math.html

---
#### <span style="color:chocolate">Exercise 6:</span> Create arrays (15 points)

1. Create and print a (3,2) numpy array of pixel values between 0 and 1.
2. Create and print a (27,) numpy array representing years from 1991 to 2017
3. Create and print a (3, 5, 10) empty numpy array
4. Create and print a (3, 5, 10) numpy array of ones
5. Create and print an array with a constant value (let's say 5) using np.ones()
6. Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.


In [7]:
# YOUR CODE HERE

#1) Create and print a (3,2) numpy array of pixel values between 0 and 1:
my_array5 = np.random.random(size = (3,2))
print('1) (3,2) numpy array:\n', my_array5)
print("*"*50)

#2) Create and print a (27, ) array representing the years from 1991 to 2017:
my_array6 = np.arange(1991, 2018, 1)
print('2) Array of years from 1991 to 2017:\n', my_array6)
print("*"*50)

# 3) Create and print a (3, 5, 10) empty numpy array:
my_array7 = np.empty(shape=(3,5,10))
print('3) (3, 5, 10) empty numpy array:\n', my_array7)
print("*"*50)

# 4) Create and print a (3, 5, 10) numpy array of ones:
my_array8 = np.ones(shape=(3,5,10))
print('4) (3, 5, 10) numpy array of ones:\n', my_array8)
print("*"*50)

# 5) Create and print an array with a constant value (let's say 5) using np.ones():
my_array9 = np.ones(shape=(3,5,10)) * 5
print('5) Array with a constant value 5:\n', my_array9)
print("*"*50)

# 6) Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.
mean = 0
std = 1
sample = 10
my_array10 = np.random.normal(mean, std, sample)
print('6) Array with random numbers from normal distribution:\n', my_array10)

1) (3,2) numpy array:
 [[0.05459259 0.5442309 ]
 [0.88670228 0.06343674]
 [0.94782539 0.41589185]]
**************************************************
2) Array of years from 1991 to 2017:
 [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
**************************************************
3) (3, 5, 10) empty numpy array:
 [[[0.00000000e+000 2.19978683e-314 0.00000000e+000 2.19978823e-314
   2.19978839e-314 2.19978830e-314 2.19978692e-314 2.19978789e-314
   2.19978822e-314 2.19978792e-314]
  [2.19978794e-314 2.19978692e-314 2.19978803e-314 2.19978794e-314
   2.19978830e-314 2.19978794e-314 2.19978631e-314 2.19978631e-314
   2.19978700e-314 2.19978692e-314]
  [2.19978739e-314 2.19978717e-314 2.19978631e-314 2.19978700e-314
   2.19978692e-314 2.19978789e-314 2.19978919e-314 2.19978883e-314
   2.19978872e-314 2.19978925e-314]
  [2.19978883e-314 2.19978692e-314 2.19978925e-314 2.19978891e-314
   2.1997888

---
#### <span style="color:chocolate">Exercise 7:</span> Reshape arrays (10 points)

Consider the following array:

In [8]:
years = np.arange(1991, 2018, 1)
print(years.shape)

(27,)


Perform the following operations on this array:
    
1. Create 3 nested arrays, each of size (3, 3). Call this array years_3d;
2. Convert the years_3d array to a flat 1D array. Call this array years_1d;
3. Add a new axis (in front) to the years_1d array. Call this array years_2d;
4. Remove the first axis from years_2d array. Call this array years_1d.

For each exercise print the array and its shape.

In [9]:
# YOUR CODE HERE

# 1) Create 3 nested arrays, each of size (3, 3). Call this array years_3d:
years_3d = years.reshape((3,3,3))
print('1) years_3d:\n', years_3d) 
print('The shape of years_3d is: ', years_3d.shape)
print("*"*50)

# 2) Convert the years_3d array to a flat 1D array and call it years_1d:
years_1d = years_3d.flatten()
print('2) years_1d:\n', years_1d)
print('The shape of years_1d is: ', years_1d.shape)
print("*"*50)

# 3) Add a new axis (in front) to the years_1d array. Call this array years_2d:
years_2d = years_1d[np.newaxis, :]
print("3) years_2d:\n", years_2d)
print("The shape of years_2d:", years_2d.shape)
print("*"*50)

# 4) Remove the first axis from years_2d. Call this array years_1d:
years_1d = years_2d.squeeze()
print('4) years_1d:\n', years_1d)
print('The shape of years_1d is: ', years_1d.shape)


1) years_3d:
 [[[1991 1992 1993]
  [1994 1995 1996]
  [1997 1998 1999]]

 [[2000 2001 2002]
  [2003 2004 2005]
  [2006 2007 2008]]

 [[2009 2010 2011]
  [2012 2013 2014]
  [2015 2016 2017]]]
The shape of years_3d is:  (3, 3, 3)
**************************************************
2) years_1d:
 [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
The shape of years_1d is:  (27,)
**************************************************
3) years_2d:
 [[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
  2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]]
The shape of years_2d: (1, 27)
**************************************************
4) years_1d:
 [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
The shape of years_1d is:  (27,)


---
#### <span style="color:chocolate">Exercise 8:</span> Joining arrays (10 points)

Provide 8 examples that use the methods <span style="color:cornflowerBlue">np.concatenate()</span> and <span style="color:cornflowerBlue">np.stack()</span>. Note: create 4 examples using each method.

In [10]:
# YOUR CODE HERE

# Create two random arrays of integer values:
array_a = np.random.randint(0, 10, size=(2,2))
print('example array_a:\n', array_a)
array_b = np.random.randint(0, 10, size=(2,2))
print('example array_b:\n', array_b)
print('*' * 50)

# Concatenate - Example 1: Concatenate along the column
array_c = np.concatenate((array_a, array_b), axis=0)
print('Example 1: Concatenate along the column:\n', array_c)

# Concatenate - Example 2: Concatenate along the rows
array_c = np.concatenate((array_a, array_b), axis=1)
print('Example 2: Concatenate along the rows:\n', array_c)

# Concatenate - Example 3: Concatenate into a single dimension
array_c = np.concatenate((array_a, array_b), axis=None)
print('Example 3: Concatenate into a single dimension:\n', array_c)

# Concatenate - Example 4: Concatenate into a single dimension, in reverse order
array_c = np.concatenate((array_b, array_a), axis=None)
print('Example 4: Concatenate into a single dimension, in reverse order:\n', array_c)
print('*' * 50)

# Stack - Example 1: Stack along axis = 0
array_c = np.stack((array_a, array_b), axis=0)
print('Example 1: Stack along axis = 0:\n', array_c)

# Stack - Example 2: Stack along axis = 1
array_c = np.stack((array_a, array_b), axis=1)
print('Example 2: Stack along axis = 1:\n', array_c)

# Stack - Example 3: Stack along axis = 2
array_c = np.stack((array_a, array_b), axis=2)
print('Example 3: Stack along axis = 2:\n', array_c)

# Stack - Example 4: Stack along axis 2, with a Transposed array
array_c = np.stack((array_a, array_b.T), axis=2)
print('Example 3: Stack along axis = 2, with a Transposed array:\n', array_c)

example array_a:
 [[0 2]
 [8 4]]
example array_b:
 [[5 0]
 [5 5]]
**************************************************
Example 1: Concatenate along the column:
 [[0 2]
 [8 4]
 [5 0]
 [5 5]]
Example 2: Concatenate along the rows:
 [[0 2 5 0]
 [8 4 5 5]]
Example 3: Concatenate into a single dimension:
 [0 2 8 4 5 0 5 5]
Example 4: Concatenate into a single dimension, in reverse order:
 [5 0 5 5 0 2 8 4]
**************************************************
Example 1: Stack along axis = 0:
 [[[0 2]
  [8 4]]

 [[5 0]
  [5 5]]]
Example 2: Stack along axis = 1:
 [[[0 2]
  [5 0]]

 [[8 4]
  [5 5]]]
Example 3: Stack along axis = 2:
 [[[0 5]
  [2 0]]

 [[8 5]
  [4 5]]]
Example 3: Stack along axis = 2, with a Transposed array:
 [[[0 5]
  [2 5]]

 [[8 0]
  [4 5]]]


---
#### <span style="color:chocolate">Numpy broadcasting</span> 

The term broadcasting describes how NumPy treats arrays during arithmetic operations. You can find more here:  https://numpy.org/doc/stable/user/basics.broadcasting.html

In [11]:
# multiplying an array with a scalar
years = np.arange(1991, 2018, 1)
years * 1

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])

In [12]:
# adding a scalar
years + 2

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019])

In [13]:
# many arithmetic operations are applied element wise on a pair of arrays
a = np.arange(3)
print('Array a:', a)
b = np.arange(3)
print('Array b:', b)
print('Sum of a and b:', a+b)

Array a: [0 1 2]
Array b: [0 1 2]
Sum of a and b: [0 2 4]


In [14]:
# another example
a = np.ones((3, 3))
print('Array a:', a)
b = np.arange(3)
print('\nArray b:', b)
print('\nSum of a and b:', a+b)

Array a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array b: [0 1 2]

Sum of a and b: [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


---
#### <span style="color:chocolate">Exercise 9:</span> Numpy array standardization (10 points)

Consider the following (10, 4) array:

In [15]:
my_array = np.random.random((10, 4))
print('my_array shape: ', my_array.shape)
my_array

my_array shape:  (10, 4)


array([[0.24177425, 0.54650481, 0.33612135, 0.94360631],
       [0.88945971, 0.04219288, 0.75481725, 0.4238639 ],
       [0.34094969, 0.57319175, 0.12192366, 0.36799589],
       [0.67983724, 0.07383442, 0.46561923, 0.00217527],
       [0.44286385, 0.75434462, 0.85281025, 0.08599301],
       [0.83815729, 0.24450164, 0.06920971, 0.54309413],
       [0.48473276, 0.03621237, 0.2021539 , 0.51697953],
       [0.97588044, 0.73063678, 0.86136654, 0.79235299],
       [0.57287389, 0.26437131, 0.23353028, 0.8504415 ],
       [0.85590617, 0.20077959, 0.25599188, 0.63539002]])

Peform the following operations on this array:
1. Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
2. Standardize and print the array and its shape using the mean and std you computed above.

In [16]:
np.random.seed(seed=1)

# YOUR CODE HERE

#1) Compute and print the mean and std for each column:
my_array_mean = my_array.mean(axis=0, keepdims=True)
print('1a) The mean of each column is:\n', my_array_mean)

my_array_std = my_array.std(axis=0, keepdims=True)
print('1b) The Standard Deviation of each column is:\n', my_array_std)
print('*' * 50)

# 2) Standardize and print the array and its shape using the mean and std you computed above: 
standardized_my_array = (my_array - my_array_mean)/(my_array_std)
print('2) The Standardized array is: \n', standardized_my_array)

1a) The mean of each column is:
 [[0.63224353 0.34665702 0.41535441 0.51618926]]
1b) The Standard Deviation of each column is:
 [[0.24029239 0.26587593 0.28708231 0.29417241]]
**************************************************
2) The Standardized array is: 
 [[-1.62497565  0.7516581  -0.27599421  1.45294746]
 [ 1.07043002 -1.14513615  1.18245826 -0.31384776]
 [-1.21224749  0.85203174 -1.02211363 -0.50376364]
 [ 0.19806584 -1.02612747  0.17508853 -1.74732222]
 [-0.78812184  1.53337536  1.52379938 -1.46239496]
 [ 0.85693001 -0.38422199 -1.20573328  0.09145955]
 [-0.61388035 -1.16762974 -0.74264592  0.00268645]
 [ 1.43007823  1.44420656  1.55360369  0.93878192]
 [-0.24707249 -0.30948912 -0.6333519   1.13624606]
 [ 0.93079372 -0.54866729 -0.55511092  0.40520715]]


----
#### <span style="color:chocolate">Bonus question:</span> Advanced (20 points)

Consider the following image:

In [17]:
my_image = np.arange(0, 1, 0.04).reshape(5,5)
print(my_image)
my_image.shape

[[0.   0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]


(5, 5)

Perform the following operations on this image (do not overwrite the original image):

1. Crop by using a border of size 1;
2. Crop by using a border of size 2;
3. Reverse the column order;
4. set to 0.5 elements divizible by 2.

In [18]:
# YOUR CODE HERE

# Finding the 'length' and 'height' of the image. In the code above, it is locked to (5,5), but I wanted to make a more general formula that could change with the user input:
my_image_height = my_image.shape[0]
my_image_length = my_image.shape[1]

# Setting the border to 1:
border = 1

# 1) Crop by using a border of size 1:
border_1 = my_image[border:my_image_length - border, border:my_image_height - border]
print('1) Image with border of 1:\n', border_1)
print('*' * 50)

# 2) Crop by using a border of size 2:

# Setting a new border size:
border = 2

border_2 = my_image[border:my_image_length - border, border:my_image_height - border]
print('2) Image with border of 1:\n', border_2)
print('*' * 50)

# 3) Reverse the column order: 
reverse_my_image = np.flip(my_image, axis=1)
print('3) Reversed image:\n', reverse_my_image)
print('*' * 50)

# 4) Set elements divisible by 2 to 0.5:
my_image[my_image % 2 == 0] = 5
print('4) Setting all elements that are divisible by 2 equal to 5:\n', my_image)


1) Image with border of 1:
 [[0.24 0.28 0.32]
 [0.44 0.48 0.52]
 [0.64 0.68 0.72]]
**************************************************
2) Image with border of 1:
 [[0.48]]
**************************************************
3) Reversed image:
 [[0.16 0.12 0.08 0.04 0.  ]
 [0.36 0.32 0.28 0.24 0.2 ]
 [0.56 0.52 0.48 0.44 0.4 ]
 [0.76 0.72 0.68 0.64 0.6 ]
 [0.96 0.92 0.88 0.84 0.8 ]]
**************************************************
4) Setting all elements that are divisible by 2 equal to 5:
 [[5.   0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]
